### ISSUE TITLE
fairygui依赖包要自己改导出脚本来实现吗？

### ISSUE THREAD

**Issue by singohgod** [Me-Maped/Gameframework-at-FairyGUI#1]

**Comment by Me-Maped** [comment]
新增了对依赖包的加载示例，见最新的提交，还未对依赖包做卸载处理，后续再继续优化

**Comment by singohgod** [comment]
还有两个小问题：
1、
![image](https://github.com/Me-Maped/Gameframework-at-FairyGUI/assets/252977/31030a2f-e035-4806-bd12-07d24fe78c58)
这里加了判断防止重复加载
2、
![image](https://github.com/Me-Maped/Gameframework-at-FairyGUI/assets/252977/5ab91a61-9f0c-43af-aeda-5fdb43e4734c)
这里的路径我这样改了后才能正常读取

**Comment by Me-Maped** [comment]
感谢指正！扩展加载路径问题已经提交，有关依赖包加载问题，原来构想是显式的在UIConfig的Depends中添加，
![image](https://github.com/Me-Maped/Gameframework-at-FairyGUI/assets/56341955/ff175710-e200-4811-922b-c44d83c6d421)
从而可以在界面卸载时移除依赖包引用或卸载依赖包。有关这一部分后续抽空会在UI包管理部分优化掉。

**Comment by Me-Maped** [comment]
1c5d910
