### ISSUE TITLE
这里的判断会导致重复加载的ui只会得到第一个加载的结果

### ISSUE THREAD

**Issue by singohgod** [Me-Maped/Gameframework-at-FairyGUI#2]
![image](https://github.com/Me-Maped/Gameframework-at-FairyGUI/assets/252977/250b328d-cc80-465d-b4a3-9c9432f4027c)

有时候ui上会需要显示多个同样的ui,比如屏幕上显示提示文本,需要弹出多个

**Comment by Me-Maped** [comment]
感谢指正，最近太忙了，后面会抽空进行优化，建议先对提示类ui单独处理。

**Comment by Me-Maped** [comment]
57d5871 已修复。测试用例见LoginForm。
