### ISSUE TITLE
框架重启会报错

### ISSUE THREAD

**Issue by laoyuan1992** [Me-Maped/Gameframework-at-FairyGUI#3]
有需求需要重启UnityGameFramework.Runtime.GameEntry.Shutdown(ShutdownType.Restart)，或者调用application.unload方法，就会到报错，请问可以解决这个问题嘛？

**Comment by Me-Maped** [comment]
感谢指出问题，会在这两天测试修复

**Comment by Me-Maped** [comment]
已修复，见Commit 831922a
